USE adlister_db;
TRUNCATE ads;
INSERT INTO ads (name, category, brand, price, description, photodir, user_id)
VALUES  ("iPhone 8", "Hardware", "Apple", 699.99,"A smartphone manufactured by Apple", "iphone-8.jpg", "1"),
    ("Galaxy S8", "Hardware", "Samsung", 599.99,"A smartphone manufactured by Samsung", "s8.jpg", "3"),
    ("Google Pixel", "Hardware", "Google", 499.99,"A smartphone manufactured by Google", "google_pixel.jpg", "4"),
    ("Microsoft Office", "Software", "Microsoft", 159.99, "A software solution for writing word documents", "office.jpg", "2"),
    ("Docker Enterprise", "Software", "Docker", 99.99, "A service for compartmentalizing software you build", "docker.jpg", "1"),
    ("Stripe Payments", "Software", "Stripe", 19.99, "A service for web developers to easily integrate online payments", "stripe.jpg", "4"),
    ("Falcon 9", "Rockets", "SpaceX", 60000000.00,"A rocket to carry humans to the planet Mars", "falcon_9.jpg", "3"),
    ("Atlas V", "Rockets", "ULA", 40000000.00,"A rocket to carry supplies to the ISS", "atlas_v.jpg", "2"),
    ("SLS", "Rockets", "Boeing", 12000000.00,"A rocket to transport humans and supplies throughout the solar system", "SLS.jpg", "3"),
    ("Pied Piper Compression", "Software","Pied Piper", 199.99,"A fast software compression service by the best business in the valley", "piedpiper.jpg", "2"),
    ("Nucleus", "Software", "Hooli", 174.99,"A crappy Pied Piper clone", "nucleus.jpg", "1"),
    ("Yo", "Software", "Or Arbel", 0.99, "An app to send people the word Yo", "yo.jpg", "4"),
    ("EndFrame", "Software", "EndFrame Corporation", 135.00, "Pied Pipers tech, stolen and rebraned", "endframe.jpg", "2"),
    ("AVIATO", "Software", "Aviato Aggregation", 29.99, "An airline booking aggregator", "Aviato.jpg", "4"),
    ("Flutterbeam", "Software", "Photo Sharing", 0.99, "A photo sharing platform", "flutterbeam.jpg", "3"),
    ("GoolyBib", "Software", "Gooly", 119.99, "Integrated multi platform functionality", "goolyBib.jpg", "1"),
    ("Raviga", "Investment", "Venture Capital", 49.99, "Series A and seed function venture capital", "raviga.jpg", "2"),
    ("Founders Fund", "Investment", "Venture Capital", 49.99, "A fund that invests primarily in science and technology companies", "founders_fund.jpg", "4"),
    ("Seqouia Capital", "Investment", "Venture Capital", 49.99, "A firm mainly focusing on the technology industry.", "seqouia.jpg", "2"),
    ("Accel Partners", "Investment", "Venture Capital", 49.99, "Accel partners with unique breakthrough ideas", "accel.jpg", "3"),
    ("Altos Ventures", "Investment", "Venture Capital", 49.99, "Invests in founder led bootstrapped companies", "altos.jpg", "1"),
    ("Draper Fisher Jurvetson", "Investment", "Venture Capital", 49.99, "Invests in early round tech startups with large potential", "DFJ.jpg", "4"),
    ("Andreessen Horowitz", "Investment", "Venture Capital", 49.99, "A Silicon Valley-based venture capital firm with $2.7 billion under management. They invest from seed to growth.", "a_h.jpg", "2"),
    ("Floodgate", "Investment", "Venture Capital", 49.99, "A venture capital fund that specializes in marketing and product management", "floodgate.jpg", "3");
